## Практическая работа

В этой практической работе пять обязательных задач.

*Обязательные задачи* помогут проверить, что вы действительно усвоили материал модуля. Сдайте их на проверку.

Удачи!

Цели практической работы: 


1.   Потренироваться в обучении модели линейной регрессии.
2.   Потренироваться в обучении модели логистической регрессии. 
3.   Потренироваться в обучении модели многослойного персептрона.





Что оценивается:

*   Все пункты и критерии приёмки по каждому заданию выполнены.
*   Код оформлен и работает корректно.





Как отправить работу на проверку:

Сдайте практическую работу этого модуля через систему контроля версий Git сервиса Skillbox GitLab. После загрузки работы на проверку напишите об этом в личном кабинете своему куратору.

В этом задании вам нужно построить модель классификации, определяющую категорию цены/цену подержанного автомобиля в зависимости от характеристик транспортного средства. 

Мы будем использовать датасет из коллекции подержанных автомобилей, выставленных на продажу в Соединенных Штатах. Он уже подготовлен, без выбросов и с категориальными фичами, преобразованными с помощью one hot encoding, и количественными фичами, стандартизированными с помощью скейлеров.


### Описание датасета:
- `id`: идентификатор записи;
- `is_manufacturer_name`: признак производителя автомобиля;

- `region_*`: регион;
- `x0_*`: тип топлива;
- `manufacturer_*`: производитель;
- `short_model_*`: сокращённая модель автомобиля;
- `title_status_*`: статус;
- `transmission_*`: коробка передач;
- `state_*`: штат;
- `age_category_*`: возрастная категория автомобиля;

- `std_scaled_odometer`: количество пройденных миль (после стандартизации);
- `year_std`: год выпуска (после стандартизации);
- `lat_std`: широта (после стандартизации);
- `long_std`: долгота (после стандартизации);
- `odometer/price_std`: отношение стоимости к пробегу автомобиля (после стандартизации);
- `desc_len_std`: количество символов в тексте объявления о продаже (после стандартизации);
- `model_in_desc_std`: количество наименований модели автомобиля в тексте объявления о продаже (после стандартизации);
- `model_len_std`: длина наименования автомобиля (после стандартизации);
- `model_word_count_std`: количество слов в наименовании автомобиля (после стандартизации);
- `month_std`: номер месяца размещения объявления о продаже автомобиля (после стандартизации);
- `dayofweek_std`: день недели размещения объявления о продаже автомобиля (после стандартизации);
- `diff_years_std`: количество лет между годом производства автомобиля и годом размещения объявления о продаже автомобиля (после стандартизации);

- `price`: стоимость;
- `price_category`: категория цены.

## Обязательные задачи

In [130]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.metrics import accuracy_score, confusion_matrix, mean_absolute_error
from sklearn.model_selection import train_test_split 
from sklearn.neural_network import MLPClassifier

In [131]:
df = pd.read_csv('vehicles_dataset_prepared.csv')
df.head()

,id,price,price_category,is_audi,is_ford,is_chevrolet,is_toyota,x0_diesel,x0_electric,x0_gas,...,long_std,year_std,odometer/price_std,desc_len_std,model_in_desc_std,model_len_std,model_word_count_std,month_std,dayofweek_std,diff_years_std
0,7308295377,54990,high,0,0,0,0,1.0,0.0,0.0,...,0.484245,1.322394,-0.510784,0.632075,-0.155788,1.163032,1.910669,-0.615846,1.120284,-1.322394
1,7316380095,16942,medium,0,1,0,0,0.0,0.0,0.0,...,1.110800,0.695973,-0.402947,-0.646781,-0.155788,0.932087,1.235799,1.623784,-1.374972,-0.695973
2,7313733749,35590,high,0,0,0,0,0.0,0.0,1.0,...,0.531185,0.852578,-0.514480,0.560744,-0.155788,0.470197,0.560930,-0.615846,-0.376870,-0.852578
3,7308210929,14500,medium,0,0,0,1,0.0,0.0,1.0,...,0.853562,0.226157,-0.241883,0.180435,-0.155788,-0.915473,-0.788810,-0.615846,1.120284,-0.226157
4,7303797340,14590,medium,0,0,0,0,0.0,0.0,0.0,...,0.557607,0.069552,-0.333074,0.766366,-0.155788,1.163032,1.910669,-0.615846,0.122182,-0.069552


**Задача 0. Линейная регрессия**

Вспомните задачу по предсказанию стоимости поддержанного автомобиля. Попробуем обучить модель линейной регрессии для предсказания цены автомобиля (колонка `price`). Для этого проделайте следующие шаги:

- Подготовьте данные: удалите колонки, которые косвенно содержат информацию о целевой переменной (`odometer/price_std`, `price_category`).
- Разделите выборку на треин и тест в отношении 70/30.
- Обучите модель линейной регрессии с дефолтными параметрами.
- Посчитайте значение метрики mae на тестовой выборке для линейной регрессии.
- Выведите получившиеся коэффициенты линейной регрессии при каждом параметре обучающей выборки с помощью метода `coef_`. Есть ли коэффициенты, которые равны нулю? Если есть, выведите названия фичей с нулевым коэффициентом
- Удалите фичи, коэффициенты которых равны нулю. И переобучите модель. Убедитесь, что значение метрики не изменилось.



In [132]:
# Ваш код здесь
X = df.drop(columns=["odometer/price_std", "price_category", "price"])
y = df["price"]
x_train, x_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.3)
lreg_model = LinearRegression()
lreg_model.fit(x_train, y_train)
lreg_model_pred = lreg_model.predict(x_test)
print(mean_absolute_error(y_test, lreg_model_pred))
print(lreg_model.coef_)

10417.43653648971
[-2.80672121e-04  8.71584070e-14  1.32884400e-13 ... -4.18147279e-11
  4.13751049e-12 -6.23002153e-12]


In [133]:
print(list(lreg_model.coef_).count(0))

136


In [134]:
zero_coef_features = [i[0] for i in list(zip(X.columns, lreg_model.coef_)) if i[1] == 0]
x_train = x_train.drop(columns=zero_coef_features)
x_test = x_test.drop(columns=zero_coef_features)
lreg_model.fit(x_train, y_train)
lreg_model_pred = lreg_model.predict(x_test)
print(mean_absolute_error(y_test, lreg_model_pred))

10417.43653648971


**Задача 1. Логистическая регрессия**

Теперь в рамках тех же данных попробуйте предсказать `price_category` с помощью алгоритма логистической регрессии. Предварительно из датафрейма удалите переменные, в которых косвенно содержится информация о целевой переменной (`odometer/price_std`, `price`). 

Для обученной модели нужно:

- рассчитать и вывести метрику качества (accuracy) на тренировочной выборке;
- сделать предикт на тестовых данных и положить его в переменную `logreg_pred`;
- рассчитать и вывести accuracy и confusion_matrix на тестовой выборке.


Задание засчитывается, если: 
- accuracy на тренировочной выборке > 87%;
- accuracy на тестовой выборке > 75.5%.

Для улучшения метрики можно преобразовывать входные данные, тюнить параметры логистической регрессии.

In [135]:
# Ваш код подготовки данных здесь. Допишите инициализацию входных фичей и целевую переменную
x = df.drop(columns=["odometer/price_std", "price", "price_category"])
y = df["price_category"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)
scaler = MinMaxScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [136]:
# Ваш код обучения моделей здесь
logreg_model = LogisticRegression(max_iter=5000, random_state=42, C=8)
logreg_model.fit(x_train_scaled, y_train)

train_pred = logreg_model.predict(x_train_scaled)
test_pred = logreg_model.predict(x_test_scaled)
print(accuracy_score(y_train, train_pred))
print(accuracy_score(y_test, test_pred))

0.8906876578048418
0.7605682605682605


**Задача 2. Многослойный персептрон**

Решите задачу, поставленную в предыдущем задании, применив модель многослойного персептрона. Добейтесь лучших значений точности на тренировочной и тестовой выборках, чем на логистической регрессии, с помощью данного алгоритма. 

Значимым увеличением точности в данном задании будем считать увеличение больше, чем на 0.01 по метрике accuracy.

In [137]:
# Ваш код здесь
x = df.drop(columns=["odometer/price_std", "price", "price_category"])
y = df["price_category"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

mlp_model = MLPClassifier(activation="tanh", hidden_layer_sizes=(200, 50, 25), max_iter=500, random_state=42)

scaler = MinMaxScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)
mlp_model.fit(x_train_scaled, y_train)
train_pred = mlp_model.predict(x_train_scaled)
test_pred = mlp_model.predict(x_test_scaled)
print(accuracy_score(y_train, train_pred))
print(accuracy_score(y_test, test_pred))

0.9952472894697757
0.7671517671517671


**Задача 3. Сравнение с древовидными моделями**

Обучите модель случайного леса на тех же данных для предсказания `price_category`. Сравните качество с моделью логистической регрессии и многослойного персептрона. Словами опишите, какая из моделей в каких случаях работает лучше по результатам на тестовой выборке, и обоснуйте свой выбор.

- **MLP работает лучше**. Лучшая обработка огромного числа признаков.

In [138]:
# Ваш код здесь
x = df.drop(columns=["odometer/price_std", "price", "price_category"])
y = df["price_category"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

scaler = MinMaxScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

rf_model = RandomForestClassifier(
    n_estimators=500,
    max_depth=200,
)
rf_model.fit(x_train_scaled, y_train)
train_pred = rf_model.predict(x_train_scaled)
test_pred = rf_model.predict(x_test_scaled)
print(accuracy_score(y_train, train_pred))
print(accuracy_score(y_test, test_pred))


1.0
0.7602217602217602


**Задача 4. Стратегия голосования**

Реализуйте стратегию голосования для предсказания целевой переменной.
Голосование в задаче классификации — это когда несколько моделей выдают свои предикты, и финальным выбирается тот предикт, который предсказали большинство моделей.

Для реализации этой стратегии проделайте следующее:

- сохраните предсказания каждой из моделей (случайный лес, многослойный персептрон, логистическая регрессия) для тестовой выборки в датафрейм `pred_df`;
- в четвертую колонку `target` положите тот класс, который предсказало большинство классификаторов. Например, если в строке были значения `high, medium, medium`, в `target` нужно положить `medium`.

     Если в строке три разных класса — `high, medium, low`, — придумайте свою стратегию по выбору значения. Самая простая стратегия: выбрать рандомно одно значение из трёх.

- посчитайте точность предсказания с помощью голосования. Выведите значения метрик accuracy и confusion_matrix.


Добейтесь значения точности > 78% 

In [140]:
pred_df = pd.DataFrame({
    'logreg': logreg_model.predict(x_test_scaled),
    'rf': rf_model.predict(x_test),
    'mlp': mlp_model.predict(x_test_scaled)
})

logreg_proba = logreg_model.predict_proba(x_test_scaled)
rf_proba = rf_model.predict_proba(x_test)
mlp_proba = mlp_model.predict_proba(x_test_scaled)

weighted = 0.65 * logreg_proba + 0.5 * rf_proba + 0.5 * mlp_proba
pred_df['target'] = logreg_model.classes_[weighted.argmax(axis=1)]

print(accuracy_score(y_test, pred_df['target']))
print(confusion_matrix(y_test, pred_df['target']))

/Library/Frameworks/Python.framework/Versions/3.15/lib/python3.15/site-packages/sklearn/utils/validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.15/lib/python3.15/site-packages/sklearn/utils/validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


0.781011781011781
[[811  27 159]
 [ 19 793 141]
 [128 158 650]]


**Примечание:**

В этом домашнем задании в задаче номер 1 и далее перед вами встал выбор: включать ли в обучение колонку `id`. При удалении данной колонки во время обучении логистической регрессии качество заметно улучшается.

Вообще обучать любую модель (будь то логистическая или линейная регрессия, или древовидный алгоритм) на данных айдишников не считается хорошей практикой. Как правило, между `id` и целевой переменной не должно быть никаких взаимосвязей. Включая колонку `id` в качества атрибута в обучение, вы стараетесь "заточить" результаты своей модели под айдишники записей. Таким образом модель обучится на некотором наборе "частных случаев", и, возможно, не обратит внимание на общие зависимости.   